[package]
name = "pdf_form"
version = "0.2.0"
authors = ["Jake <jsandler18@gmail.com>"]
readme = "README.md"
keywords = ["pdf", "form"]
description = "A library for programatically filling out pdf forms"
license = "MIT"

[dependencies]
bitflags = "^1.2"
derive-error = "^0.0.4"
lopdf = "^0.25"
